export const users = [
  {
    email: "hani@gmail.com",
    password: "123456",
  },
];

export const recommended = [
  {
    img: "https://geeks-react.netlify.app/static/media/course-laravel.48ab426cd3f0adc40dd9.jpg",
    title:
      "Laravel: The Ultimate Beginner's Guide to Learn Laravel Step by Step",
    duration: "2h 46m",
    level: "2h 46m",
    rate: "2.5",
    count: 1000,
    price: "600",
    priceAfterDiscount: "500",
    instructor: "Jenny",
  },
  {
    img: "https://geeks-react.netlify.app/static/media/course-node.291fe1cded8ebab181ab.jpg",
    title: "Beginning Node.js, Express & MongoDB Development",
    duration: "2h 40m",
    level: "2h 40m",
    rate: "2.5",
    count: 1000,
    price: "600",
    priceAfterDiscount: "500",
    instructor: "Jenny",
  },
  {
    img: "https://geeks-react.netlify.app/static/media/course-python.0e5358f9e53a89fd75bd.jpg",
    title: "The Python Course: build web application",
    duration: "2h 46m",
    level: "2h 46m",
    rate: "2.5",
    count: 1000,
    price: "600",
    priceAfterDiscount: "500",
    instructor: "Jenny",
  },
  {
    img: "https://geeks-react.netlify.app/static/media/course-laravel.48ab426cd3f0adc40dd9.jpg",
    title:
      "Laravel: The Ultimate Beginner’s Guide to Learn Laravel Step by Step",
    duration: "1h 46m",
    level: "1h 46m",
    rate: "2.5",
    count: 1000,
    price: "600",
    priceAfterDiscount: "500",
    instructor: "Jenny",
  },
  {
    img: "https://geeks-react.netlify.app/static/media/course-react.999d5d4b7ef4771200c2.jpg",
    title: "How to easily create a website with React",
    duration: "2h 40m",
    level: "2h 40m",
    rate: "2.5",
    count: 1000,
    price: "600",
    priceAfterDiscount: "500",
    instructor: "Jenny",
  },
  {
    img: "https://geeks-react.netlify.app/static/media/course-angular.8553e67e04af598d0cc4.jpg",
    title: "Angular - the complete guide for beginner",
    duration: "6h 00m",
    level: "6h 00m",
    rate: "2.5",
    count: 1000,
    price: "600",
    priceAfterDiscount: "500",
    instructor: "Jenny",
  },
  {
    img: "https://geeks-react.netlify.app/static/media/course-gatsby.460be4ebbf9db1ccfe5d.jpg",
    title: "Revolutionize how you build the web",
    duration: "6h 46m",
    level: "6h 46m",
    rate: "2.5",
    count: 1000,
    price: "600",
    priceAfterDiscount: "500",
    instructor: "Jenny",
  },
  {
    img: "https://geeks-react.netlify.app/static/media/course-graphql.f5dec42e4ae0102ebffa.jpg",
    title: "GraphQL: introduction to graphQL for beginners",
    duration: "5h 46m",
    level: "5h 46m",
    rate: "2.5",
    count: 1000,
    price: "600",
    priceAfterDiscount: "500",
    instructor: "Jenny",
  },
  {
    img: "https://geeks-react.netlify.app/static/media/course-angular.8553e67e04af598d0cc4.jpg",
    title: "Angular - the complete guide for beginner",
    duration: "3h 30m",
    level: "3h 30m",
    rate: "2.5",
    count: 1000,
    price: "600",
    priceAfterDiscount: "500",
    instructor: "Jenny",
  },
  {
    img: "https://geeks-react.netlify.app/static/media/course-laravel.48ab426cd3f0adc40dd9.jpg",
    title:
      "Laravel: The Ultimate Beginner’s Guide to Learn Laravel Step by Step",
    duration: "2h 46m",
    level: "2h 46m",
    rate: "2.5",
    count: 1000,
    price: "600",
    priceAfterDiscount: "500",
    instructor: "Jenny",
  },
  {
    img: "https://geeks-react.netlify.app/static/media/course-node.291fe1cded8ebab181ab.jpg",
    title: "Beginning Node.js, Express & MongoDB Development",
    duration: "2h 46m",
    level: "2h 46m",
    rate: "2.5",
    count: 1000,
    price: "600",
    priceAfterDiscount: "500",
    instructor: "Jenny",
  },
  {
    img: "https://geeks-react.netlify.app/static/media/course-javascript.8afdeff32816e30422da.jpg",
    title: "Applying JavaScript and using the console.",
    duration: "2h 46m",
    level: "2h 46m",
    rate: "2.5",
    count: 1000,
    price: "600",
    priceAfterDiscount: "500",
    instructor: "Jenny",
  },
  {
    img: "https://geeks-react.netlify.app/static/media/course-css.e2fee8ac50e018baa8fc.jpg",
    title: "CSS: ultimate CSS course from beginner to advanced",
    duration: "1h 30m",
    level: "1h 30m",
    rate: "2.5",
    count: 1000,
    price: "600",
    priceAfterDiscount: "500",
    instructor: "Jenny",
  },
  {
    img: "https://geeks-react.netlify.app/static/media/course-wordpress.d8a212a8a44f7edaccfb.jpg",
    title: "Wordpress: complete WordPress theme & plugin development",
    duration: "1h 30m",
    level: "1h 30m",
    rate: "2.5",
    count: 1000,
    price: "600",
    priceAfterDiscount: "500",
    instructor: "Jenny",
  },
  {
    img: "https://geeks-react.netlify.app/static/media/course-angular.8553e67e04af598d0cc4.jpg",
    title: "Angular - the complete guide for beginner",
    duration: "3h 30m",
    level: "3h 30m",
    rate: "2.5",
    count: 1000,
    price: "600",
    priceAfterDiscount: "500",
    instructor: "Jenny",
  },
  {
    img: "https://geeks-react.netlify.app/static/media/course-laravel.48ab426cd3f0adc40dd9.jpg",
    title:
      "Laravel: The Ultimate Beginner’s Guide to Learn Laravel Step by Step",
    duration: "2h 46m",
    level: "2h 46m",
    rate: "2.5",
    count: 1000,
    price: "600",
    priceAfterDiscount: "500",
    instructor: "Jenny",
  },
  {
    img: "https://geeks-react.netlify.app/static/media/course-node.291fe1cded8ebab181ab.jpg",
    title: "Beginning Node.js, Express & MongoDB Development",
    duration: "2h 46m",
    level: "2h 46m",
    rate: "2.5",
    count: 1000,
    price: "600",
    priceAfterDiscount: "500",
    instructor: "Jenny",
  },
  {
    img: "https://geeks-react.netlify.app/static/media/course-javascript.8afdeff32816e30422da.jpg",
    title: "Applying JavaScript and using the console.",
    duration: "2h 46m",
    level: "2h 46m",
    rate: "2.5",
    count: 1000,
    price: "600",
    priceAfterDiscount: "500",
    instructor: "Jenny",
  },

  {
    img: "https://geeks-react.netlify.app/static/media/course-angular.8553e67e04af598d0cc4.jpg",
    title: "Angular - the complete guide for beginner",
    duration: "6h 00m",
    level: "6h 00m",
    rate: "2.5",
    count: 1000,
    price: "600",
    priceAfterDiscount: "500",
    instructor: "Jenny",
  },
  {
    img: "https://geeks-react.netlify.app/static/media/course-gatsby.460be4ebbf9db1ccfe5d.jpg",
    title: "Revolutionize how you build the web",
    duration: "6h 46m",
    level: "6h 46m",
    rate: "2.5",
    count: 1000,
    price: "600",
    priceAfterDiscount: "500",
    instructor: "Jenny",
  },
  {
    img: "https://geeks-react.netlify.app/static/media/course-graphql.f5dec42e4ae0102ebffa.jpg",
    title: "GraphQL: introduction to graphQL for beginners",
    duration: "5h 46m",
    level: "5h 46m",
    rate: "2.5",
    count: 1000,
    price: "600",
    priceAfterDiscount: "500",
    instructor: "Jenny",
  },
  {
    img: "https://geeks-react.netlify.app/static/media/course-angular.8553e67e04af598d0cc4.jpg",
    title: "Angular - the complete guide for beginner",
    duration: "3h 30m",
    level: "3h 30m",
    rate: "2.5",
    count: 1000,
    price: "600",
    priceAfterDiscount: "500",
    instructor: "Jenny",
  },
  {
    img: "https://geeks-react.netlify.app/static/media/course-laravel.48ab426cd3f0adc40dd9.jpg",
    title:
      "Laravel: The Ultimate Beginner’s Guide to Learn Laravel Step by Step",
    duration: "2h 46m",
    level: "2h 46m",
    rate: "2.5",
    count: 1000,
    price: "600",
    priceAfterDiscount: "500",
    instructor: "Jenny",
  },
];

export const popular = [
  {
    img: "https://geeks-react.netlify.app/static/media/course-laravel.48ab426cd3f0adc40dd9.jpg",
    title:
      "Laravel: The Ultimate Beginner’s Guide to Learn Laravel Step by Step",
    duration: "2h 46m",
    level: "2h 46m",
    rate: "2.5",
    count: 1000,
    price: "600",
    priceAfterDiscount: "500",
    instructor: "Jenny",
  },
  {
    img: "https://geeks-react.netlify.app/static/media/course-node.291fe1cded8ebab181ab.jpg",
    title: "Beginning Node.js, Express & MongoDB Development",
    duration: "2h 46m",
    level: "2h 46m",
    rate: "2.5",
    count: 1000,
    price: "600",
    priceAfterDiscount: "500",
    instructor: "Jenny",
  },
  {
    img: "https://geeks-react.netlify.app/static/media/course-javascript.8afdeff32816e30422da.jpg",
    title: "Applying JavaScript and using the console.",
    duration: "2h 46m",
    level: "2h 46m",
    rate: "2.5",
    count: 1000,
    price: "600",
    priceAfterDiscount: "500",
    instructor: "Jenny",
  },
  {
    img: "https://geeks-react.netlify.app/static/media/course-gatsby.460be4ebbf9db1ccfe5d.jpg",
    title: "Revolutionize how you build the web",
    duration: "1h 46m",
    level: "1h 46m",
    rate: "2.5",
    count: 1000,
    price: "600",
    priceAfterDiscount: "500",
    instructor: "Jenny",
  },
  {
    img: "https://geeks-react.netlify.app/static/media/course-html.427d9d6b3af64832dbc2.jpg",
    title: "HTML Full Course - Build a Website Tutorial",
    duration: "3h 16m",
    level: "3h 16m",
    rate: "2.5",
    count: 1000,
    price: "600",
    priceAfterDiscount: "500",
    instructor: "Jenny",
  },
  {
    img: "https://geeks-react.netlify.app/static/media/course-node.291fe1cded8ebab181ab.jpg",
    title: "Beginning Node.js, Express & MongoDB Development",
    duration: "2h 00m",
    level: "2h 00m",
    rate: "2.5",
    count: 1000,
    price: "600",
    priceAfterDiscount: "500",
    instructor: "Jenny",
  },
  {
    img: "https://geeks-react.netlify.app/static/media/course-laravel.48ab426cd3f0adc40dd9.jpg",
    title:
      "Laravel: The Ultimate Beginner’s Guide to Learn Laravel Step by Step",
    duration: "1h 00m",
    level: "1h 00m",
    rate: "2.5",
    count: 1000,
    price: "600",
    priceAfterDiscount: "500",
    instructor: "Jenny",
  },
  {
    img: "https://geeks-react.netlify.app/static/media/course-react.999d5d4b7ef4771200c2.jpg",
    title: "How to easily create a website with React",
    duration: "3h 55m",
    level: "3h 55m",
    rate: "2.5",
    count: 1000,
    price: "600",
    priceAfterDiscount: "500",
    instructor: "Jenny",
  },
  {
    img: "https://geeks-react.netlify.app/static/media/course-angular.8553e67e04af598d0cc4.jpg",
    title: "Angular - the complete guide for beginner",
    duration: "2h 46m",
    level: "2h 46m",
    rate: "2.5",
    count: 1000,
    price: "600",
    priceAfterDiscount: "500",
    instructor: "Jenny",
  },
  {
    img: "https://geeks-react.netlify.app/static/media/course-laravel.48ab426cd3f0adc40dd9.jpg",
    title:
      "Laravel: The Ultimate Beginner's Guide to Learn Laravel Step by Step",
    duration: "2h 46m",
    level: "2h 46m",
    rate: "2.5",
    count: 1000,
    price: "600",
    priceAfterDiscount: "500",
    instructor: "Jenny",
  },
  {
    img: "https://geeks-react.netlify.app/static/media/course-node.291fe1cded8ebab181ab.jpg",
    title: "Beginning Node.js, Express & MongoDB Development",
    duration: "2h 40m",
    level: "2h 40m",
    rate: "2.5",
    count: 1000,
    price: "600",
    priceAfterDiscount: "500",
    instructor: "Jenny",
  },
  {
    img: "https://geeks-react.netlify.app/static/media/course-python.0e5358f9e53a89fd75bd.jpg",
    title: "The Python Course: build web application",
    duration: "2h 46m",
    level: "2h 46m",
    rate: "2.5",
    count: 1000,
    price: "600",
    priceAfterDiscount: "500",
    instructor: "Jenny",
  },
  {
    img: "https://geeks-react.netlify.app/static/media/course-laravel.48ab426cd3f0adc40dd9.jpg",
    title:
      "Laravel: The Ultimate Beginner’s Guide to Learn Laravel Step by Step",
    duration: "1h 46m",
    level: "1h 46m",
    rate: "2.5",
    count: 1000,
    price: "600",
    priceAfterDiscount: "500",
    instructor: "Jenny",
  },
  {
    img: "https://geeks-react.netlify.app/static/media/course-react.999d5d4b7ef4771200c2.jpg",
    title: "How to easily create a website with React",
    duration: "2h 40m",
    level: "2h 40m",
    rate: "2.5",
    count: 1000,
    price: "600",
    priceAfterDiscount: "500",
    instructor: "Jenny",
  },
  {
    img: "https://geeks-react.netlify.app/static/media/course-angular.8553e67e04af598d0cc4.jpg",
    title: "Angular - the complete guide for beginner",
    duration: "6h 00m",
    level: "6h 00m",
    rate: "2.5",
    count: 1000,
    price: "600",
    priceAfterDiscount: "500",
    instructor: "Jenny",
  },
];
